Created the .env file to store the token
rexdivakar/Notifly pull request #38
Opened 2021-01-01 11:47 UTC by aakash-cse

2021-01-01 13:18 UTC, rexdivakar commented
![image](https://user-images.githubusercontent.com/15235122/103439331-f58b0700-4c61-11eb-980f-56c477038421.png)
Why is this failing please check @aakash-cse

2021-01-02 13:41 UTC, SanchitJain123 requested changes
@aakash-cse it would be better if we could provide different token for Slack, Discord, and Telegram.

2021-01-02 20:10 UTC, aakash-cse commented
> @aakash-cse it would be better if we could provide different token for Slack, Discord, and Telegram.

I don't know why it is failing since I haven't modified much of the working codr

2021-01-03 02:36 UTC, rexdivakar commented
It is failing since the token is picked up as a whole string, Please add tokens for slack and telegram and run the test in parallel !! @aakash-cse 

![image](https://user-images.githubusercontent.com/15235122/103470618-7e0cc300-4d9a-11eb-8c38-871c2f200a3e.png)

2021-01-03 06:42 UTC, SanchitJain123 commented
> > @aakash-cse it would be better if we could provide different token for Slack, Discord, and Telegram.
> 
> I don't know why it is failing since I haven't modified much of the working codr

as @rexdivakar said it should be `r'` not `"r'`. Please try again after changing this

2021-01-03 07:41 UTC, SanchitJain123 commented on .env
> +TOKEN=r"https://discord.com/api/webhooks/771253998313144321/5FNBsAi8-exyc-3rxLOYudQdQqMdpcaCOqCh6z1IX4ledG1oGyaONeIY1HDUns6qBZhW"
try removing `r` itself

2021-01-06 16:45 UTC, SanchitJain123 commented
the problem now here is that the pytest is not using the environment variable.

2021-01-10 06:10 UTC, SanchitJain123 commented
sorry was busy for a while can we connect on discord @aakash-cse , message me on sanchit#5988

2021-01-12 16:17 UTC, SanchitJain123 approved these changes

2021-01-12 16:18 UTC, merged

2021-01-12 16:18 UTC, SanchitJain123 commented
thank you @aakash-cse